version: '3.8'

services:
  northstar:
    image: ghcr.io/fjiayang/northstar:latest
    container_name: northstar
    restart: unless-stopped
    ports:
      - "30001:443"
      - "51688:51688"
    environment:
      - NS_USER=voting
      - NS_PWD=JLxfPeXLT7JfM3
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms1g -Xmx2g -XX:+UseG1GC
    volumes:
      - /home/fjy/container/northstar/data:/northstar-dist/data
      - /home/fjy/container/northstar/logs:/northstar-dist/logs
      - /home/fjy/container/northstar/config/.northstar-salt:/root/.northstar-salt